### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by rrelmy** [briancollins/BCTabBarController#12]
Is it planned to support iPads?

On the iPad 2 with iOS 5.0.1 are several issues.
- The white line is still there in landscape and portrait mode
- landscape: tabbar only shows a subset of icons (the rest of the bar is black, but icons can be tapped and then show up)
- landscape: the tabbar is placed too low
- some more

**Comment by briancollins** [comment]
Hi,

Increasing the width of the bar image should fix these issues.

On 20 January 2012 08:49, rrelmy
reply@reply.github.com
wrote:

**Comment by rrelmy** [comment]
Using icons with a size of 40x40 pixel fixed the issue that not all of the icons were visible.
But the other issues remained.

probably because i used a navigation controller?

I ended up write a custom TabBarController implementation from scratch, which is done more like the original UITabBarController.

There is another problem with BCTabBar, if you have a ViewController that does not support a orientation and you change to the tab in the unsupported orientation you will see it in the unsupported orientation.
The standard UITabBarController behaviour is that the TabBarController only supports orientation supported by all its ViewControllers.

**Comment by frodoz** [comment]
hey rrelmy, 

any chance you'll release your iPad version?

thanks!

**Comment by rrelmy** [comment]
No, I can't at least not now.
